Feature/upload picture wall
Mezzanine-UI/mezzanine pull request #123
Opened 2021-12-28 09:55 UTC by ting-ting-ting

2022-01-03 09:17 UTC, travor20814 requested changes
1. props 的註解要記得寫
2. 要記得 a-z 的排序

2022-01-03 09:17 UTC, travor20814 commented on packages/react/src/Upload/UploadPictureWall.tsx
> +          // eslint-disable-next-line react/no-array-index-key
這行多了

2022-01-03 10:13 UTC, ting-ting-ting commented
type 跟 storybook 都更新了

2022-01-05 06:06 UTC, travor20814 approved these changes

2022-01-05 06:10 UTC, merged