feat(react/notification): implement
Mezzanine-UI/mezzanine pull request #25
Opened 2021-02-26 09:47 UTC by Kuanisinajar

2021-03-29 10:14 UTC, travor20814 requested changes
Some types are broken.

<img width="737" alt="截圖 2021-03-29 下午6 08 31" src="https://user-images.githubusercontent.com/17423836/112822385-74091080-90ba-11eb-8c3f-d3e06efbc596.png">

2021-03-29 10:14 UTC, travor20814 commented on packages/core/src/notification/notification.ts
> +  serverityIcon: `${notificationPrefix}__serverity-icon`,
typo: serverity => severity

2021-03-29 10:14 UTC, travor20814 commented on packages/core/src/notification/_notification.scss
> +$severities: severity.$severities-for-feedback;
renamed after rebase `main` branch
`$severities-for-feedback` => `$severities-wth-info`

2021-05-11 08:28 UTC, Kuanisinajar commented
2021/05/11:
- refactor: `Notifier` configs extensible
- feat: `Notifier` has `getConfig` method
- refactor: `Message` add slide-fade transition

2021-05-11 12:18 UTC, travor20814 requested changes

2021-05-11 12:18 UTC, travor20814 commented on packages/core/src/notification/notification.ts
> +  sererityIcon: `${notificationPrefix}__serverity-icon`,
typo serverity => severity

2021-05-11 12:18 UTC, travor20814 commented on packages/core/src/notification/_notification-styles.scss
> +  &__serverity-icon {
typo serverity => severity

2021-05-11 12:18 UTC, travor20814 commented on packages/react/src/Notification/Notification.tsx
> +import React, {
no need to import `React`

2021-05-12 06:18 UTC, travor20814 approved these changes

2021-05-12 06:28 UTC, merged