Feat/stepper
Mezzanine-UI/mezzanine pull request #73
Opened 2021-05-24 22:54 UTC by BenChen21

2021-05-25 06:49 UTC, Kuanisinajar reviewed
整體上要注意：
- 樣式的部分用 dash-base 統一。原因是 scss 在解析的時候會把駝峰的變數名稱大寫改小寫，所以必須使用 dash-base。
- 不要使用 gap & gap 只在 flex-box, grid 有用
- 避免使用 for，使用 array.forEach
- 盡量使用 jsx.map 的方式去處理而不是 loop 之後寫進一個 const 
- 如果不是複雜計算的 jsx element，直接寫在 return 的 jsx 底下

2021-05-25 06:49 UTC, kuaniscreative commented on packages/core/src/stepper/_stepper-styles.scss
> +@mixin circleIcon($size:24px) {
size 的部分用變數去給 default，目的是讓使用者可以透過 config 去改。

ex:
`$icon-size: 24px !default;`

`@mixin circleIcon($size: $icon-size) { ... }`

2021-05-25 06:49 UTC, Kuanisinajar commented on packages/core/src/stepper/_stepper-styles.scss
> +  &__connectorBar {
connect bar 建議使用 :after 搭配 :last-child 的方式，把這些 css 屬性放到 step 下面。原因是 `Stepper` 這個 component 不需要直接去處理 step 的樣式邏輯

2021-05-25 06:49 UTC, Kuanisinajar commented on packages/core/src/stepper/_stepper-styles.scss
> +    @include step;
不需要重複寫入一次 host style。把 host class 綁到 component 身上即可

2021-05-25 06:49 UTC, Kuanisinajar commented on packages/core/src/stepper/_stepper-styles.scss
> +  &__iconContainer {
- 使用 dash-base
- container 這個字有點多餘，他底下只有 text content

2021-05-25 06:49 UTC, Kuanisinajar commented on packages/core/src/stepper/_stepper-styles.scss
> +    @include circleIcon(24px);
重複寫入，一直會在的樣式直接寫一個 class 綁到 component 身上即可

2021-05-25 06:49 UTC, Kuanisinajar commented on packages/core/src/stepper/_stepper-styles.scss
> +  &--disabled > &__iconContainer {
使用 css var 去做 background-color 的處理。

例如說：
`&--disabled {
  --#{$step-prefix}--background-color: palette.color(disabled);
}`

icon 只要一直吃 var(--#{$step-prefix}--background-color)，不用多一個 class 去控制

2021-05-25 06:49 UTC, Kuanisinajar commented on packages/core/src/stepper/_stepper-styles.scss
> +    width: 100%;
icon 使用 font-size 去控制大小

2021-05-25 06:49 UTC, Kuanisinajar commented on packages/core/src/stepper/step.ts
> +export const stepPrefix = `${stepperPrefix}-step` as const;
as const 多餘

2021-05-25 06:49 UTC, Kuanisinajar commented on packages/react/src/Stepper/Step.tsx
> +  last?: boolean;
沒用到的 prop

2021-05-25 06:49 UTC, Kuanisinajar commented on packages/react/src/Stepper/Step.tsx
> +        disabled ? classes.disabled : classes.host,
之前提到的，host class 應該一直都有，可避免樣式重複寫入

2021-05-25 06:49 UTC, Kuanisinajar commented on packages/react/src/Stepper/Stepper.stories.tsx
> +  for (let index = 0; index < stepCount; index += 1) {
雖然是 story，但希望未來類似情境可以用 map 的方式而不是 for loop

例如：

```jsx
const Example = () => {
  return (
    <div>
      {yourData.map((d) => {
        return (
          <span>
            {d}
          </span>
        )
      })}
    </div>
  )
}
```

2021-05-25 06:49 UTC, Kuanisinajar commented on packages/react/src/Stepper/Stepper.stories.tsx
> +        gap: '16px',
gap 沒有用，而且支援度不夠好，不要使用

2021-05-25 06:49 UTC, Kuanisinajar commented on packages/react/src/Stepper/Stepper.tsx
> +    activeStep = -1,
`activeIndex` 完全由使用者控制，有 default value 很奇怪

2021-05-25 06:49 UTC, Kuanisinajar commented on packages/react/src/Stepper/Stepper.tsx
> +  const connectorBar = (<span className={classes.connectorBar} />);
同上面說的，建議用 :after 搭配 :last-child 的方式做到 step 的樣式裡面，不需要單獨做一個 element 給他。這樣還有另外一個好處就是 stepper 不用再受限於這個 connectorBar，可以只處理每個 step 該有的狀態就好。

2021-05-25 06:49 UTC, Kuanisinajar commented on packages/react/src/Stepper/Stepper.tsx
> +  for (let i = 0; i < childrenArray.length; i += 1) {
用 Array.forEach 的方式而不是 for，比較好讀。而在這裡也建議使用 children.map 的方式直接用 jsx 的方式寫，也會比較清楚架構長相如何

2021-05-25 06:49 UTC, Kuanisinajar commented on packages/react/src/index.ts
> +export {
Step 相關的東西沒有 export

2021-05-25 06:49 UTC, Kuanisinajar commented on packages/react/src/Stepper/Stepper.tsx
> +    }
這塊可以合併起來

```js
const state = {
  active: activeStep === i
}
```

2021-05-25 06:49 UTC, Kuanisinajar commented on packages/core/src/stepper/_stepper-styles.scss
> +  gap: spacing.level(2);
不要使用 gap，支援度還不夠好

2021-05-26 06:21 UTC, BenChen21 commented on packages/core/src/stepper/_stepper-styles.scss
> +  &__iconContainer {
這個容器底下可能是icon

2021-05-27 08:58 UTC, BenChen21 commented on packages/react/src/Stepper/Stepper.stories.tsx
> +  for (let index = 0; index < stepCount; index += 1) {
這邊是要列舉 activeStep 0~4 的情境   不是要塞step的資料進stepper

2021-05-27 09:38 UTC, BenChen21 commented on packages/core/src/stepper/_stepper-styles.scss
> +    width: 100%;
__completedIcon 裡面是塞<Icon />不是step的數字

2021-06-01 06:08 UTC, travor20814 requested changes

2021-06-01 06:08 UTC, travor20814 commented on packages/react/src/Stepper/Stepper.stories.tsx
> +  for (let index = 0; index < stepCount; index += 1) {
這邊也是要用上面 State 提到的方式改

2021-06-01 06:08 UTC, travor20814 commented on packages/react/src/Stepper/Stepper.stories.tsx
> +  for (let activeStep = -1; activeStep < 4; activeStep += 1) {
這邊冠群的意思是像這樣
`Array.from(Array(N))` 用這方式建造一個給定 Ｎ 長度的 array，然後再利用 index 轉出你要的東西
或是你一開始就把 array 的初始值給好
`const basicSteps = [-1, 0, 1, 2, 3];` 再用它去 map 結果
這兩種都比起用 for loop 清楚多，而且不用額外宣告 for loop 用的常數跟 push 增加額外風險
![截圖 2021-06-01 下午2 01 19](https://user-images.githubusercontent.com/17423836/120274051-e1673680-c2e1-11eb-80ca-fa529d0d7432.png)

2021-06-01 07:03 UTC, travor20814 approved these changes

2021-06-01 07:05 UTC, merged